apiVersion: v1
kind: Service
metadata:
  name: {{ include "Pom-v7.dnsName" . }}
  labels:
    app.kubernetes.io/name: {{ include "Pom-v7.fullname" . }}
    helm.sh/chart: {{ include "Pom-v7.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.service.annotations}}
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val }}
    {{- end}}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "Pom-v7.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
